services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: always
    tty: true
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    depends_on:
      - mysql8
    networks:
      - webserver

  mysql8:
    image: mysql:8.0
    container_name: mysql8
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
    networks:
      - webserver

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "8029:80"
    volumes:
      - ./:/var/www
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
      - ./.docker/nginx/log:/var/log/nginx
    depends_on:
      - app
    networks:
      - webserver

networks:
  webserver:
    driver: bridge
